CREATE DATABASE cricket_db;
USE cricket_db;

CREATE TABLE CRICKET_DATA (
    id INT,
    p_match INT,
    inns INT
    bat VARCHAR(255),
    p_bat VARCHAR(255),
    team_bat VARCHAR(255),
    bowl VARCHAR(255),
    p_bowl VARCHAR(255),
    team_bowl VARCHAR(255),
    ball INT,
    ball_id INT,
    outcome VARCHAR(255),
    score VARCHAR(255),
    `out` BOOLEAN,
    dismissal VARCHAR(255),
    p_out INT,
    `over` DECIMAL(5,2),
    noball BOOLEAN,
    wide BOOLEAN,
    byes INT,
    legbyes INT,
    cur_bat_runs TINYINT UNSIGNED,
    cur_bat_bf SMALLINT UNSIGNED,
    cur_bowl_ovr DECIMAL(3,1),
    cur_bowl_wkts TINYINT UNSIGNED,
    cur_bowl_runs SMALLINT UNSIGNED,
    inns_runs INT,
    wkts INT,
    inns_balls INT,
    inns_runs INT,
    inns_wkts INT,
    `target` INT,
    max_balls INT,
    `date` DATE,
    `year` INT,
    ground VARCHAR(255),
    country VARCHAR(255),
    winner VARCHAR(255),
    toss VARCHAR(255),
    competitor VARCHAR(255),
    bat_hand VARCHAR(255),
    bowl_style VARCHAR(255),
    kind_bat_runs VARCHAR(255),
    ballfaced INT,
    bowlruns INT,
    bat_out BOOLEAN,
    rain BOOLEAN,
    daynight BOOLEAN,
    gmt_offset INT,
    wagonX INT,
    wagonY INT,
    wagonZ INT,
    `length` VARCHAR(255),
    shot VARCHAR(255),
    `control` BOOLEAN,
    predscore INT,
    predprob DECIMAL(5,4),
    PRIMARY KEY (p_match_inns, ball_id)
);

CREATE INDEX idx_match ON cricket (p_match_inns);